-- Enum types
DROP TYPE IF EXISTS CHUNK_TYPE CASCADE;
DROP TYPE IF EXISTS SEVERITY CASCADE;

-- Tables
DROP TABLE IF EXISTS alarm_module CASCADE;
DROP TABLE IF EXISTS document CASCADE;
DROP TABLE IF EXISTS document_chunks CASCADE;
DROP TABLE IF EXISTS alarm_code CASCADE;
DROP TABLE IF EXISTS heading CASCADE;
DROP TABLE IF EXISTS response CASCADE;
DROP TABLE IF EXISTS chunk_headings CASCADE;
DROP TABLE IF EXISTS response_sources CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS users CASCADE;